<img src="Logo.png" width="100" align="left"/> 

# <center> Unit 3 Project </center>
#  <center> Fourth section : Conclusion </center>


In this notebook you will be comparing the results of the two methods we used on the created testset. That is said: you will compare the results to the clustering with the results of the classification on the same test test and provide insights and explanation about the observed behaviour.

For this final task you will need to : 
1. Load the testset data that you created all along this project 
2. For each cluster provide percentages about each actual/ predicted class contained with this cluster. Eg : cluster N°2 : is made of ( 50% class 2 and 50% class 3 ) from actual labels and ( 40 % predicted class 2 and 40% predicted class 3 + 20% predicted class 1) 
The above is just an example and is far away from the actual situation.

3. Explain the behaviour and provide isights about it

## 1.  Load the data:

In [1]:
import pandas as pd

In [5]:
# To-Do : load the test summary data 
df = pd.read_csv("test_summary.csv")
df= df.drop(["Unnamed: 0"],axis = 1)

In [6]:
y_true = df['Category']
y_pred = df['cluster']

In [7]:
df

,ID,Age,Category,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,cluster,Predicted_class
0,1,32,0,0,38.5,52.50000,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0,3,0
1,2,32,0,0,38.5,70.30000,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5,3,0
2,3,32,0,0,46.9,74.70000,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3,3,0
3,4,32,0,0,43.2,52.00000,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7,3,0
4,5,32,0,0,39.2,74.10000,32.6,24.8,9.6,9.15,4.32,76.0,29.9,68.7,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,611,62,4,1,32.0,416.60000,5.9,110.3,50.0,5.57,6.30,55.7,650.9,68.5,2,4
611,612,64,4,1,24.0,102.80000,2.9,44.4,20.0,1.54,3.02,63.0,35.9,71.3,3,4
612,613,64,4,1,29.0,87.30000,3.5,99.0,48.0,1.66,3.63,66.7,64.2,82.0,1,4
613,614,46,4,1,33.0,68.28392,39.0,62.0,20.0,3.56,4.20,52.0,50.0,71.0,4,4
614,615,59,4,1,36.0,68.28392,100.0,80.0,12.0,9.07,5.30,67.0,34.0,68.0,4,4

## 2. Analysis:

In [8]:
# To-Do create a summary about each cluster : 
cluster=[]
predict_class=[]
true_class0=[]
true_class1=[]
true_class2=[]
true_class3=[]
true_class4=[]

predict_class0=[]
predict_class1=[]
predict_class2=[]
predict_class3=[]
predict_class4=[]

for value in df['cluster']:
    cluster.append(value)


# percentages of each target (actual Category) within each cluster 
# + Percentages of each predicted class within the cluster 
# results should be something like : 
# For clusterk : {'true_class0_percetage': 0.0,
#                 'true_class1_percetage': 0.0,
#                  'true_class2_percetage': 0.0,
#                   'true_class3_percetage': 0.0,
#                   'true_class4_percetage': 0.0,
#                   'predicted_class0_percetage': 0.0,
#                   'predicted_class1_percetage': 0.0,
#                   'predicted_class2_percetage': 0.0,
#                   'predicted_class3_percetage': 0.0,
#                    'predicted_class4_percetage': 0.0}

In [9]:
true_label=[]
for i in df['Category']:
    true_label.append(i)

In [10]:
for j in df['Predicted_class']:
    predict_class.append(j)

In [11]:
for values in range(0,len(cluster)):
    if cluster[values]==0: 
        true_class0.append(true_label[values])
        predict_class0.append(predict_class[values])
    if cluster[values]==1: 
        true_class1.append(true_label[values])
        predict_class1.append(predict_class[values])
    if cluster[values]==2:
        true_class2.append(true_label[values])
        predict_class2.append(predict_class[values])
    if cluster[values]==3:
        true_class3.append(true_label[values])
        predict_class3.append(predict_class[values])
    if cluster[values]==4:
        true_class4.append(true_label[values])
        predict_class4.append(predict_class[values])

In [12]:
from collections import Counter
print(Counter(true_class0))
print(Counter(true_class1))
print(Counter(true_class2))
print(Counter(true_class3))
print(Counter(true_class4))
print(len(true_class0))

Counter({4: 3})
Counter({4: 16, 2: 3, 3: 3, 0: 1, 1: 1})
Counter({4: 4, 1: 2, 2: 2})
Counter({0: 437, 2: 10, 3: 2, 1: 1, 4: 1})
Counter({0: 95, 3: 16, 2: 9, 4: 6, 1: 3})
3

In [18]:
list1=[true_class0,true_class1,true_class2,true_class3,true_class4]

In [15]:
list0=[Counter(true_class0),Counter(true_class1),Counter(true_class2),Counter(true_class3),Counter(true_class4)]

In [16]:
list_predict=[predict_class0,predict_class1,predict_class2,predict_class3,predict_class4]
list_predict_counter=[Counter(predict_class0),Counter(predict_class1),Counter(predict_class2),Counter(predict_class3),Counter(predict_class4)]

## 3. Explanations and isights :

In [19]:
# in this section you should display analysis about each cluster and comment those one by one 
for i in range(0,len(list0)):
    print()
    print("For cluster " + format(i))
    print()
    for j in range(0,5):
        print("true_class " + format(j) + " percentage: " + format(list[i][j]/len(list1[i])))
    for x in range(0,5):
        print("predict_class " + format(x) + " percentage: " + format(list_predict_counter[i][x]/len(list_predict[i])))

For cluster 0

true_class 0 percentage: 0.0
true_class 1 percentage: 0.0
true_class 2 percentage: 0.0
true_class 3 percentage: 0.0
true_class 4 percentage: 1.0
predict_class 0 percentage: 0.0
predict_class 1 percentage: 0.0
predict_class 2 percentage: 0.0
predict_class 3 percentage: 0.0
predict_class 4 percentage: 1.0

For cluster 1

true_class 0 percentage: 0.041666666666666664
true_class 1 percentage: 0.041666666666666664
true_class 2 percentage: 0.125
true_class 3 percentage: 0.125
true_class 4 percentage: 0.6666666666666666
predict_class 0 percentage: 0.041666666666666664
predict_class 1 percentage: 0.041666666666666664
predict_class 2 percentage: 0.16666666666666666
predict_class 3 percentage: 0.08333333333333333
predict_class 4 percentage: 0.6666666666666666

For cluster 2

true_class 0 percentage: 0.0
true_class 1 percentage: 0.25
true_class 2 percentage: 0.25
true_class 3 percentage: 0.0
true_class 4 percentage: 0.5
predict_class 0 percentage: 0.0
predict_class 1 percentage: 0.25
predict_class 2 percentage: 0.0
predict_class 3 percentage: 0.0
predict_class 4 percentage: 0.75

For cluster 3

true_class 0 percentage: 0.9689578713968958
true_class 1 percentage: 0.0022172949002217295
true_class 2 percentage: 0.022172949002217297
true_class 3 percentage: 0.004434589800443459
true_class 4 percentage: 0.0022172949002217295
predict_class 0 percentage: 0.9733924611973392
predict_class 1 percentage: 0.0022172949002217295
predict_class 2 percentage: 0.017738359201773836
predict_class 3 percentage: 0.004434589800443459
predict_class 4 percentage: 0.0022172949002217295

For cluster 4

true_class 0 percentage: 0.7364341085271318
true_class 1 percentage: 0.023255813953488372
true_class 2 percentage: 0.06976744186046512
true_class 3 percentage: 0.12403100775193798
true_class 4 percentage: 0.046511627906976744
predict_class 0 percentage: 0.7596899224806202
predict_class 1 percentage: 0.023255813953488372
predict_class 2 percentage: 0.06201550387596899
predict_class 3 percentage: 0.09302325581395349
predict_class 4 percentage: 0.06201550387596899

Cluster 0 : we can clearly see that the cluster number 0 contain 100% the category number 4 "Cirrhosis" and the same thing for the predict one! nothing about the other categories 

Cluster 1 : 4 % from both class 0 and 1 , 12,5% both of class 2 and 3 and end with 66% from class 4 in the true labels,
for the predicted values , we have te same in the true labels... 4% in both of class 1 and 2, 16% in class 2 and 8% in class 3 and 66% class 4

Cluster 2 : contain 50% of true class 4 which refer to the category "Cirrhosis" and contain 25% of both category 1 and 2 which refer to "suspect Blood Donor" and "Hepatitis"
for the predicted one , it's formed from 25% with class 1 "suspect Blood Donor" and 75% from class 4

Cluster 3 : for the true label percentage, we have 96 % in class 0 and 2% in class 2 and nearly some null values in the other classes
for the predicted percentage , we got 97,3% in class 0 , 1.7% in class 2 and nearly some null values for the rest of classes

Cluster 4 : for the last cluster, we have 73% in class 1, 2% for class 1, 6% for class 2, 12% for class 3, 4% class 4
for the predicted one, 76% for class 0 , 2% for class 1, 5% for class 2, 9% for class 3 and 6% for class 4 with is near from the true label one

## 4. Conclusion:

Explain your findings and provide reasons for the behaviour.

We can clearly see that we had a different result result for both methods. Classification is the process of classifying the data with the help of class labels. On the other hand, Clustering is similar to classification but there are no predefined class labels, that's why we had a different result between them.

for the unsupervied learning, we had some different values from many classes.
for some clusters like the third one , we had 96% form class 0 in the true label.

In the end the two method gives a different result, the right method will be choosed depent on the case and the problem.